const commons = (file) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}`;
const appleWiki = (file) => `https://theapplewiki.com/wiki/Special:Redirect/file/${encodeURIComponent(file)}`;

const img = {
  iphone15pro: commons('iPhone 15 Pro.jpg'),
  iphone15: commons('Apple iPhone 15.jpg'),
  iphone15pm: commons('iPhone 15 Pro Max.jpg'),
  s25u: commons('Samsung Galaxy S25 Ultra 2025.jpg'),
  s24u: commons('Samsung Galaxy S24 Ultra 2024.jpg'),
  a55: commons('Samsung Galaxy A55 5G 2024.jpg'),
  pixel8: commons('Google Pixel 8 Pro.jpg'),
  oneplus13: commons('OnePlus 13 back.jpg'),
  xiaomi13: commons('Xiaomi 13.jpg'),
  huaweiP60: commons('Huawei P60 Pro.jpg'),
  air15: commons('MacBook Air (15-inch, M4, Silver).jpg'),
  air13: commons('MacBook Air (13-inch, M4, Silver).jpg'),
  airM1: commons('MacBook Air .jpg'),
  macpro: commons('Mac Book Pro.jpg'),
  surface7: commons('Microsoft Surface Laptop 7.jpg'),
  spectre: commons('Hp Spectre x360.jpg'),
  thinkpad: commons('Thinkpad X1 Carbon.jpg'),
  rog: commons('ASUS ROG Zephyrus 2026-08-15 G14.jpg'),
  ipadpro: commons('IPad Pro.jpg'),
  ipadair: commons('IPad Air 5th Generation 2024.jpg'),
  airpodspro: commons('AirPods Pro.jpg'),
  airpodsmax: commons('Apple AirPods Max.jpg'),
  buds2: commons('Samsung Galaxy Buds2.jpg'),
  buds: commons('Samsung Galaxy Buds.jpg'),
  galaxywatch: commons('Samsung Galaxy Watch 2026-08-11 Ultra 4.jpg'),
  applewatch: commons('Apple watch.jpg'),
  ps5slim: commons('Playstation 5 modèle slim (édition standard avec lecteur de disque amovible.png'),
  ps5: commons('Playstation 5.jpg'),
  xbox: commons('Xbox Series X (July 8, 2026).jpg'),
  switch: commons('Nintendo Switch OLED.jpg'),
  dualsense: commons('Playstation 5 DualSense controller in Midnight Black, 2026-02-07 (front).jpg'),
  mx3s: commons('Logitech MX Master 3S HS21.jpg'),
  jbl4: commons('JBL Charge 4 1v2.jpg'),
  iphone14: commons('IPhone 14 Pro.jpg'), galaxyS23: commons('Samsung Galaxy S23 Ultra.jpg'), pixel9: commons('Google Pixel 9 Pro XL.jpg'),
  macpro16: commons('MacBook Pro 16-inch M3 Max.jpg'), dellxps: commons('Dell XPS 13 9343.jpg'), hpenvy: commons('HP Envy x360 2022.jpg'),
  ipadmini: commons('IPad mini 6th generation.jpg'), tabS9: commons('Samsung Galaxy Tab S9.jpg'), sonyxm5: commons('Sony WH-1000XM5.jpg'), boseqc: commons('Bose QuietComfort Ultra Headphones.jpg'),
  soundcore: commons('Anker Soundcore Motion Boom.jpg'), watchultra: commons('Apple Watch Ultra 2.jpg'), garmin: commons('Garmin Venu 3.jpg'), ps5digital: commons('PlayStation 5 Digital Edition.jpg'),
  xboxs: commons('Xbox Series S.jpg'), steamdeck: commons('Steam Deck OLED.jpg'), logikeys: commons('Logitech MX Keys.jpg'), keychron: commons('Keychron K2.jpg'),
  ankercharger: commons('Anker Nano II charger.jpg'), belkinpower: commons('Belkin power bank.jpg'), samsungssd: commons('Samsung Portable SSD T7.jpg'), wdpassport: commons('WD My Passport.jpg'),
  canonr50: commons('Canon EOS R50.jpg'), djimini: commons('DJI Mini 4 Pro.jpg'), gopro12: commons('GoPro HERO12 Black.jpg'), kindle: commons('Kindle Paperwhite 5.jpg'),
  quest3: commons('Meta Quest 3.jpg'), chromecast: commons('Chromecast with Google TV.jpg'), roku: commons('Roku Streaming Stick 4K.jpg'), nesthub: commons('Google Nest Hub 2nd gen.jpg')
};

const photo = (key, credit='Wikimedia Commons') => ({ url: img[key], credit });
const p = (id,name,brand,category,price,stock,ram,storage,badge,key,description,specs) => ({
  id,name,brand,category,price,stock,ram,storage,badge,rating:4.8,reviews:Math.floor(35+id.length*7),
  images:[img[key]], imageCredit:photo(key).credit, imageSource:'Wikimedia Commons', description, specs
});

export const PRODUCTS = [
 p('iphone-17-pro-max','Apple iPhone 17 Pro Max 256GB','Apple','Phones',1299,7,'12GB','256GB','New','iphone15pm','Next-generation Pro Max concept listing with a large display, pro cameras and all-day battery.',{Display:'6.9-inch Super Retina XDR',Chip:'Apple silicon',Camera:'Pro camera system',Port:'USB-C'}),
 p('iphone-18-pro','Apple iPhone 18 Pro 256GB','Apple','Phones',1399,5,'12GB','256GB','New','iphone15pro','Next-generation Pro iPhone concept listing with premium design and advanced camera features.',{Display:'6.3-inch Super Retina XDR',Chip:'Apple silicon',Camera:'Pro camera system',Port:'USB-C'}),
 p('iphone-15','Apple iPhone 15 128GB','Apple','Phones',699,12,'6GB','128GB','New','iphone15','USB-C iPhone with A16 Bionic performance and a 48MP main camera.',{Display:'6.1-inch Super Retina XDR',Chip:'A16 Bionic',Camera:'48MP Main',Port:'USB-C'}),
 p('galaxy-s25-ultra','Samsung Galaxy S25 Ultra 256GB','Samsung','Phones',1299,6,'12GB','256GB','New','s25u','Ultra flagship with S Pen, high-resolution cameras and a large Dynamic AMOLED display.',{Display:'6.9-inch Dynamic AMOLED 2X',Chip:'Snapdragon 8 Elite',Camera:'200MP Main',Battery:'5000mAh',Pen:'S Pen'}),
 p('galaxy-s24-ultra','Samsung Galaxy S24 Ultra 512GB','Samsung','Phones',999,8,'12GB','512GB','Sale','s24u','Titanium-framed Galaxy Ultra with S Pen and a versatile camera system.',{Display:'6.8-inch Dynamic AMOLED 2X',Chip:'Snapdragon 8 Gen 3',Camera:'200MP Main',Battery:'5000mAh',Pen:'S Pen'}),
 p('galaxy-a55-5g','Samsung Galaxy A55 5G 256GB','Samsung','Phones',349,15,'8GB','256GB','Popular','a55','Premium mid-range Galaxy phone with a 120Hz display and 5G connectivity.',{Display:'6.6-inch Super AMOLED 120Hz',Chip:'Exynos 1480',Camera:'50MP Main',Battery:'5000mAh'}),
 p('pixel-8-pro','Google Pixel 8 Pro 128GB','Google','Phones',699,9,'12GB','128GB','Popular','pixel8','Google flagship with Tensor G3 and a pro camera system.',{Display:'6.7-inch LTPO OLED',Chip:'Google Tensor G3',Camera:'50MP Main',OS:'Android'}),
 p('oneplus-13','OnePlus 13 256GB','OnePlus','Phones',899,10,'12GB','256GB','New','oneplus13','High-performance Android flagship with a large AMOLED display and triple camera system.',{Display:'6.82-inch LTPO AMOLED',Chip:'Snapdragon 8 Elite',Camera:'50MP Triple Camera',Battery:'6000mAh'}),
 p('xiaomi-13','Xiaomi 13 256GB','Xiaomi','Phones',549,11,'8GB','256GB','Sale','xiaomi13','Compact flagship with Leica-inspired imaging and a bright AMOLED display.',{Display:'6.36-inch AMOLED 120Hz',Chip:'Snapdragon 8 Gen 2',Camera:'50MP Triple Camera',Battery:'4500mAh'}),
 p('huawei-p60-pro','Huawei P60 Pro','Huawei','Phones',599,6,'8GB','256GB','Limited','huaweiP60','Premium camera phone with a distinctive pearlescent finish and OLED display.',{Display:'6.67-inch LTPO OLED',Chip:'Snapdragon 8+ Gen 1 4G',Camera:'48MP XMAGE',Battery:'4815mAh'}),
 p('macbook-air-15-m4','Apple MacBook Air 15-inch M4','Apple','Laptops',1199,5,'16GB','512GB','New','air15','Thin 15-inch MacBook Air with Apple silicon performance and a large Liquid Retina display.',{Display:'15.3-inch Liquid Retina',Chip:'Apple M4',Memory:'16GB',Storage:'512GB SSD'}),
 p('macbook-air-13-m4','Apple MacBook Air 13-inch M4','Apple','Laptops',999,7,'16GB','256GB','New','air13','Lightweight MacBook Air with M4 performance and long battery life.',{Display:'13.6-inch Liquid Retina',Chip:'Apple M4',Memory:'16GB',Storage:'256GB SSD'}),
 p('macbook-air-m1','Apple MacBook Air M1 13-inch','Apple','Laptops',699,4,'8GB','256GB','Sale','airM1','Fanless MacBook Air powered by the M1 chip.',{Display:'13.3-inch Retina',Chip:'Apple M1',Memory:'8GB',Storage:'256GB SSD'}),
 p('macbook-pro-14','Apple MacBook Pro 14-inch','Apple','Laptops',1599,4,'16GB','512GB','Popular','macpro','Pro notebook built for demanding creative and development workloads.',{Display:'14.2-inch Liquid Retina XDR',Chip:'Apple silicon',Memory:'16GB',Storage:'512GB SSD'}),
 p('surface-laptop-7','Microsoft Surface Laptop 7','Microsoft','Laptops',1299,6,'16GB','512GB','New','surface7','Premium Windows laptop with a high-resolution touchscreen and modern Snapdragon platform.',{Display:'13.8-inch PixelSense',Chip:'Snapdragon X Plus',Memory:'16GB',Storage:'512GB SSD'}),
 p('hp-spectre-x360','HP Spectre x360 13','HP','Laptops',999,5,'16GB','512GB','Popular','spectre','Convertible premium Windows laptop with a 360-degree hinge.',{Display:'13.5-inch Touch',CPU:'Intel Core i7',Memory:'16GB',Storage:'512GB SSD'}),
 p('thinkpad-x1-carbon','Lenovo ThinkPad X1 Carbon','Lenovo','Laptops',1199,6,'16GB','512GB','Popular','thinkpad','Business-class ThinkPad with a lightweight chassis and productivity-focused keyboard.',{Display:'14-inch',CPU:'Intel Core i7',Memory:'16GB',Storage:'512GB SSD'}),
 p('rog-zephyrus-g14','ASUS ROG Zephyrus G14','ASUS','Laptops',1699,3,'32GB','1TB','Limited','rog','Compact gaming and creator laptop with a high-performance GPU platform.',{Display:'14-inch',CPU:'AMD Ryzen',Memory:'32GB',Storage:'1TB SSD',GPU:'GeForce RTX'}),
 p('ipad-pro-129','Apple iPad Pro 12.9-inch','Apple','Tablets',1099,5,'8GB','256GB','Popular','ipadpro','Large professional iPad designed for creative work and productivity.',{Display:'12.9-inch Liquid Retina XDR',Chip:'Apple silicon',Storage:'256GB',Port:'USB-C'}),
 p('ipad-air-5','Apple iPad Air 5th Gen','Apple','Tablets',599,9,'8GB','256GB','Sale','ipadair','Versatile iPad Air with Apple silicon and support for professional accessories.',{Display:'10.9-inch Liquid Retina',Chip:'Apple M1',Storage:'256GB',Port:'USB-C'}),
 p('airpods-pro-2','Apple AirPods Pro 2nd Gen','Apple','Audio',249,18,'—','—','New','airpodspro','In-ear wireless earbuds with active noise cancellation and a USB-C case.',{Audio:'Active Noise Cancellation',Charging:'USB-C',Wireless:'Bluetooth',Battery:'All-day with case'}),
 p('airpods-max','Apple AirPods Max','Apple','Audio',549,5,'—','—','Popular','airpodsmax','Over-ear wireless headphones with premium materials and active noise cancellation.',{Audio:'Active Noise Cancellation',Wireless:'Bluetooth',Controls:'Digital Crown',Battery:'Up to 20 hours'}),
 p('galaxy-buds2-pro','Samsung Galaxy Buds2 Pro','Samsung','Audio',179,14,'—','—','Sale','buds2','Compact Galaxy earbuds with immersive audio and active noise cancellation.',{Audio:'Hi-Fi 24-bit',Wireless:'Bluetooth',ANC:'Yes',Water:'IPX7'}),
 p('galaxy-buds','Samsung Galaxy Buds','Samsung','Audio',99,12,'—','—','Sale','buds','Compact true-wireless earbuds designed for everyday listening.',{Audio:'Wireless Stereo',Wireless:'Bluetooth',Case:'Charging case',Battery:'All-day'}),
 p('galaxy-watch7','Samsung Galaxy Watch7','Samsung','Wearables',299,8,'—','44mm','New','galaxywatch','Modern Samsung smartwatch for health, fitness and everyday notifications.',{Display:'AMOLED',Connectivity:'Bluetooth',Water:'5ATM',OS:'Wear OS'}),
 p('apple-watch-series-9','Apple Watch Series 9','Apple','Wearables',349,7,'—','45mm','Popular','applewatch','Apple smartwatch for fitness, notifications, calls and everyday tracking.',{Display:'Retina OLED',Chip:'S9 SiP',Connectivity:'GPS',Water:'50m'}),
 p('ps5-slim','Sony PlayStation 5 Slim Disc Edition','Sony','Gaming',499,4,'—','1TB','Popular','ps5slim','Slim PlayStation 5 console with detachable disc drive.',{Storage:'1TB SSD',Video:'4K HDR',Drive:'Blu-ray',Controller:'DualSense'}),
 p('ps5-console','Sony PlayStation 5 Disc Edition','Sony','Gaming',449,3,'—','825GB','Sale','ps5','Current-generation PlayStation console with fast SSD storage and 4K gaming.',{Storage:'825GB SSD',Video:'4K HDR',Drive:'Blu-ray',Controller:'DualSense'}),
 p('xbox-series-x','Microsoft Xbox Series X','Microsoft','Gaming',499,5,'—','1TB','Popular','xbox','Powerful Xbox console with 4K gaming and quick resume.',{Storage:'1TB SSD',Video:'4K UHD',Resolution:'Up to 4K',Controller:'Xbox Wireless'}),
 p('switch-oled','Nintendo Switch OLED Model','Nintendo','Gaming',349,6,'—','64GB','Popular','switch','Hybrid console with a vibrant 7-inch OLED display and detachable controllers.',{Display:'7-inch OLED',Storage:'64GB',Mode:'Handheld / TV',Controller:'Joy-Con'}),
 p('dualsense-midnight','Sony DualSense Wireless Controller Midnight Black','Sony','Gaming',79,10,'—','—','New','dualsense','Wireless PS5 controller with adaptive triggers and haptic feedback.',{Wireless:'Bluetooth',Haptics:'Yes',Triggers:'Adaptive',Port:'USB-C'}),
 p('mx-master-3s','Logitech MX Master 3S','Logitech','Accessories',99,13,'—','—','Popular','mx3s','Premium ergonomic wireless mouse for productivity and multi-device workflows.',{Sensor:'8,000 DPI',Wireless:'Bluetooth / Bolt',Buttons:'7',Battery:'Up to 70 days'}),
 p('jbl-charge-4','JBL Charge 4','JBL','Audio',129,12,'—','—','Sale','jbl4','Portable Bluetooth speaker with powerful sound and a rugged design.',{Wireless:'Bluetooth',Battery:'Up to 20 hours',Water:'IPX7',Powerbank:'Yes'}),
 p('iphone-15-pro-blue','Apple iPhone 15 Pro 256GB Blue Titanium','Apple','Phones',829,4,'8GB','256GB','Limited','iphone15pro','Blue Titanium iPhone 15 Pro variant with A17 Pro and USB-C.',{Display:'6.1-inch Super Retina XDR',Chip:'A17 Pro',Camera:'48MP Main',Color:'Blue Titanium'}),
 p('galaxy-s25-ultra-silver','Samsung Galaxy S25 Ultra Titanium Silver Blue','Samsung','Phones',1349,4,'12GB','256GB','Limited','s25u','Titanium Galaxy Ultra variant with S Pen and advanced cameras.',{Display:'6.9-inch Dynamic AMOLED 2X',Chip:'Snapdragon 8 Elite',Camera:'200MP Main',Color:'Titanium Silver Blue'}),
 p('pixel-8-pro-obsidian','Google Pixel 8 Pro Obsidian 256GB','Google','Phones',729,5,'12GB','256GB','Sale','pixel8','Pixel 8 Pro variant with Google Tensor G3 and pro camera controls.',{Display:'6.7-inch LTPO OLED',Chip:'Tensor G3',Camera:'50MP Main',Color:'Obsidian'}),
 p('ipad-air-5-purple','Apple iPad Air 5th Gen 256GB','Apple','Tablets',629,6,'8GB','256GB','Popular','ipadair','iPad Air 5th generation with M1 performance and USB-C.',{Display:'10.9-inch Liquid Retina',Chip:'Apple M1',Storage:'256GB',Port:'USB-C'}),
 p('thinkpad-x1-carbon-gen7','Lenovo ThinkPad X1 Carbon Gen 7','Lenovo','Laptops',699,5,'16GB','512GB','Sale','thinkpad','Lightweight business ultrabook with the classic ThinkPad keyboard.',{Display:'14-inch',CPU:'Intel Core i7',Memory:'16GB',Storage:'512GB SSD'}),
 p('ipad-pro-129-space-gray','Apple iPad Pro 12.9-inch Space Gray','Apple','Tablets',1049,4,'8GB','256GB','Sale','ipadpro','Professional large-format iPad in Space Gray.',{Display:'12.9-inch',Chip:'Apple silicon',Storage:'256GB',Color:'Space Gray'}),
 p('airpods-max-black','Apple AirPods Max Black','Apple','Audio',579,3,'—','—','Limited','airpodsmax','Premium over-ear Apple headphones in a dark finish.',{Audio:'Active Noise Cancellation',Wireless:'Bluetooth',Battery:'Up to 20 hours',Color:'Black'}),
 p('iphone-14-pro','Apple iPhone 14 Pro 256GB','Apple','Phones',799,7,'6GB','256GB','Popular','iphone14','Pro iPhone with Dynamic Island, a 48MP camera and premium stainless steel design.',{Display:'6.1-inch Super Retina XDR',Chip:'A16 Bionic',Camera:'48MP Main',Port:'Lightning'}),
 p('galaxy-s23-ultra','Samsung Galaxy S23 Ultra 256GB','Samsung','Phones',899,6,'12GB','256GB','Popular','galaxyS23','Samsung flagship with S Pen, four cameras and a bright Dynamic AMOLED display.',{Display:'6.8-inch Dynamic AMOLED 2X',Chip:'Snapdragon 8 Gen 2',Camera:'200MP Main',Pen:'S Pen'}),
 p('pixel-9-pro-xl','Google Pixel 9 Pro XL 256GB','Google','Phones',999,6,'16GB','256GB','New','pixel9','Google flagship with advanced computational photography and a smooth OLED display.',{Display:'6.8-inch LTPO OLED',Chip:'Google Tensor',Camera:'Triple Pro Camera',OS:'Android'}),
 p('macbook-pro-16-m3','Apple MacBook Pro 16-inch M3 Max','Apple','Laptops',2499,3,'36GB','1TB','Limited','macpro16','Professional MacBook built for demanding creative and development workloads.',{Display:'16.2-inch Liquid Retina XDR',Chip:'Apple M3 Max',Memory:'36GB',Storage:'1TB SSD'}),
 p('dell-xps-13','Dell XPS 13','Dell','Laptops',1199,5,'16GB','512GB','Popular','dellxps','Premium compact Windows laptop with a high-resolution display and lightweight chassis.',{Display:'13.4-inch',CPU:'Intel Core Ultra',Memory:'16GB',Storage:'512GB SSD'}),
 p('hp-envy-x360','HP Envy x360 14','HP','Laptops',899,6,'16GB','512GB','New','hpenvy','Convertible touchscreen laptop for work, study and everyday creative tasks.',{Display:'14-inch Touch',CPU:'AMD Ryzen',Memory:'16GB',Storage:'512GB SSD'}),
 p('ipad-mini-6','Apple iPad mini 6th Gen','Apple','Tablets',499,8,'4GB','256GB','Popular','ipadmini','Compact iPad with Apple silicon, USB-C and support for Apple Pencil.',{Display:'8.3-inch Liquid Retina',Chip:'Apple A15 Bionic',Storage:'256GB',Port:'USB-C'}),
 p('galaxy-tab-s9','Samsung Galaxy Tab S9','Samsung','Tablets',699,7,'8GB','128GB','New','tabS9','Premium Android tablet with an AMOLED display and S Pen support.',{Display:'11-inch Dynamic AMOLED 2X',Chip:'Snapdragon 8 Gen 2',Storage:'128GB',Water:'IP68'}),
 p('sony-wh1000xm5','Sony WH-1000XM5','Sony','Audio',349,8,'—','—','Popular','sonyxm5','Wireless noise-cancelling headphones with detailed sound and long battery life.',{Audio:'Noise cancelling',Wireless:'Bluetooth',Battery:'Up to 30 hours',Microphone:'Built-in'}),
 p('bose-quietcomfort-ultra','Bose QuietComfort Ultra Headphones','Bose','Audio',429,5,'—','—','New','boseqc','Premium immersive headphones with advanced noise cancellation.',{Audio:'Immersive Audio',Wireless:'Bluetooth',Battery:'Up to 24 hours',Controls:'Touch'}),
 p('soundcore-motion-boom','Anker Soundcore Motion Boom','Anker','Audio',109,10,'—','—','Sale','soundcore','Portable outdoor Bluetooth speaker with powerful stereo sound.',{Wireless:'Bluetooth',Battery:'Up to 24 hours',Water:'IPX7',Powerbank:'Yes'}),
 p('apple-watch-ultra-2','Apple Watch Ultra 2','Apple','Wearables',799,4,'—','49mm','Limited','watchultra','Rugged Apple smartwatch for sport, health and outdoor adventure.',{Display:'49mm Retina OLED',Chip:'S9 SiP',Connectivity:'GPS + Cellular',Water:'100m'}),
 p('garmin-venu-3','Garmin Venu 3','Garmin','Wearables',449,6,'—','45mm','Popular','garmin','Health and fitness smartwatch with GPS and long battery life.',{Display:'AMOLED',Connectivity:'GPS',Battery:'Up to 14 days',Water:'5ATM'}),
 p('ps5-digital','Sony PlayStation 5 Digital Edition','Sony','Gaming',399,5,'—','825GB','Popular','ps5digital','Disc-free PlayStation 5 console with fast SSD storage and 4K gaming.',{Storage:'825GB SSD',Video:'4K HDR',Drive:'Digital',Controller:'DualSense'}),
 p('xbox-series-s','Microsoft Xbox Series S','Microsoft','Gaming',299,8,'—','512GB','Popular','xboxs','Compact all-digital Xbox console for next-generation gaming.',{Storage:'512GB SSD',Video:'1440p',Drive:'Digital',Controller:'Xbox Wireless'}),
 p('steam-deck-oled','Valve Steam Deck OLED','Valve','Gaming',549,5,'16GB','512GB','New','steamdeck','Handheld gaming PC with a vibrant OLED display and Steam library access.',{Display:'7.4-inch OLED',CPU:'AMD APU',Memory:'16GB',Storage:'512GB SSD'}),
 p('logitech-mx-keys','Logitech MX Keys','Logitech','Accessories',109,10,'—','—','Popular','logikeys','Wireless productivity keyboard designed for multi-device workspaces.',{Wireless:'Bluetooth / Bolt',Layout:'Full size',Backlight:'Smart illumination',Battery:'Up to 5 months'}),
 p('keychron-k2','Keychron K2 Wireless Mechanical Keyboard','Keychron','Accessories',89,12,'—','—','Popular','keychron','Compact wireless mechanical keyboard with hot-swappable productivity layout.',{Wireless:'Bluetooth',Layout:'75%',Switches:'Mechanical',Backlight:'RGB'}),
 p('anker-nano-ii','Anker Nano II 65W Charger','Anker','Accessories',39,20,'—','—','New','ankercharger','Compact USB-C GaN charger for phones, tablets and laptops.',{Power:'65W',Ports:'USB-C',Technology:'GaN',Safety:'MultiProtect'}),
 p('belkin-power-bank','Belkin 20K Power Bank','Belkin','Accessories',59,14,'—','20,000mAh','Popular','belkinpower','Portable battery pack with high-capacity charging for mobile devices.',{Capacity:'20,000mAh',Ports:'USB-C + USB-A',Output:'20W',Charging:'Fast charge'}),
 p('samsung-t7-ssd','Samsung Portable SSD T7 1TB','Samsung','Accessories',99,9,'—','1TB','Popular','samsungssd','Fast portable solid-state drive with USB-C connectivity.',{Storage:'1TB SSD',Interface:'USB 3.2',Read:'Up to 1,050MB/s',Security:'AES 256-bit'}),
 p('wd-my-passport','WD My Passport 2TB','Western Digital','Accessories',69,11,'—','2TB','Sale','wdpassport','Portable external hard drive for everyday backups and file storage.',{Storage:'2TB HDD',Interface:'USB 3.0',Compatibility:'Windows / macOS',Backup:'Included software'}),
 p('canon-eos-r50','Canon EOS R50','Canon','Cameras',679,4,'—','24MP','New','canonr50','Compact mirrorless camera for photography and creator video.',{Sensor:'APS-C CMOS',Video:'4K UHD',Mount:'RF mount',Focus:'Dual Pixel CMOS AF'}),
 p('dji-mini-4-pro','DJI Mini 4 Pro','DJI','Cameras',759,4,'—','—','New','djimini','Lightweight camera drone with omnidirectional obstacle sensing.',{Video:'4K HDR',Weight:'Under 249g',Flight:'Up to 34 minutes',Camera:'48MP'}),
 p('gopro-hero12','GoPro HERO12 Black','GoPro','Cameras',399,7,'—','—','Popular','gopro12','Rugged action camera for stabilized outdoor video.',{Video:'5.3K60',Water:'10m',Stabilization:'HyperSmooth',Wireless:'Wi-Fi + Bluetooth'}),
 p('kindle-paperwhite','Amazon Kindle Paperwhite','Amazon','Tablets',149,10,'—','16GB','Popular','kindle','Waterproof e-reader with a sharp glare-free display.',{Display:'6.8-inch',Storage:'16GB',Water:'IPX8',Battery:'Weeks'}),
 p('meta-quest-3','Meta Quest 3','Meta','Gaming',499,5,'8GB','128GB','New','quest3','Mixed-reality headset for immersive games and experiences.',{Display:'4K+',Memory:'8GB',Storage:'128GB',Tracking:'Inside-out'}),
 p('chromecast-google-tv','Chromecast with Google TV','Google','Accessories',49,13,'—','8GB','Popular','chromecast','Streaming media player with 4K HDR and voice remote.',{Video:'4K HDR',OS:'Google TV',Wireless:'Wi-Fi',Remote:'Voice remote'}),
 p('roku-streaming-stick','Roku Streaming Stick 4K','Roku','Accessories',49,12,'—','—','Sale','roku','Compact streaming player with 4K HDR entertainment.',{Video:'4K HDR',Wireless:'Wi-Fi',OS:'Roku',Remote:'Voice remote'}),
 p('google-nest-hub','Google Nest Hub 2nd Gen','Google','Accessories',99,8,'—','—','Popular','nesthub','Smart home display for media, routines and connected devices.',{Display:'7-inch',Assistant:'Google Assistant',Audio:'Full-range speaker',Connectivity:'Wi-Fi'})
];

export const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
